version: "3.9"

services:
  db:
    image: postgres:15
    container_name: siuu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gobank
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: siuu-bank-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:gobank@db:5432/postgres?sslmode=disable
      JWT_SECRET: siuu-secret
    command: ["./bank-server"]

volumes:
  pgdata:
